export const ROUTES = {
  index: {
    path: "/",
    name: "Index",
    requiresAuth: false,
  },
  login: {
    path: "/login",
    name: "Login",
    requiresAuth: false,
  },
  users: {
    path: "/users",
    name: "Users",
    requiresAuth: true,
    title: "Users",
    canAcceess: ["super_admin"],
  },
  dashboard: {
    path: "/dashboard",
    name: "Dashboard",
    requiresAuth: true,
    title: "Dashboard Overview",
    canAcceess: [
      "super_admin",
      "accountant",
      "customer_service",
      "internal_control_manager",
      "business_development_manager",
    ],
  },
  category: {
    path: "/category",
    name: "Category",
    requiresAuth: true,
    title: "Category",
    canAcceess: [
      "super_admin",
      "accountant",
      "internal_control_manager",
      "business_development_manager",
    ],
  },
  warehouse: {
    path: "/warehouse",
    name: "Warehouse",
    requiresAuth: true,
    title: "Warehouse",
    canAcceess: [
      "super_admin",
      "accountant",
      "internal_control_manager",
      "business_development_manager",
    ],
  },
  product: {
    path: "/product",
    name: "Product",
    requiresAuth: true,
    title: "Product",
    canAcceess: [
      "super_admin",
      "accountant",
      "internal_control_manager",
      "business_development_manager",
    ],
  },
  orders: {
    path: "/orders",
    name: "Orders",
    requiresAuth: true,
    title: "Orders Management",
    canAcceess: [
      "super_admin",
      "accountant",
      "customer_service",
      "internal_control_manager",
      "business_development_manager",
    ],
  },

  view_orders: {
    path: "/order/:id",
    name: "ViewOrders",
    requiresAuth: true,
    title: "View Order",
    canAcceess: [
      "super_admin",
      "accountant",
      "customer_service",
      "internal_control_manager",
      "business_development_manager",
    ],
  },
  order_return: {
    path: "/orders/returned-order",
    name: "ReeturnedOrders",
    requiresAuth: true,
    title: "Return Processing",
    canAcceess: [
      "super_admin",
      "accountant",
      "customer_service",
      "internal_control_manager",
      "business_development_manager",
    ],
  },
  customer: {
    path: "/customers",
    name: "Customers",
    requiresAuth: true,
    title: "Customer Management",
    canAcceess: [
      "super_admin",
      "accountant",
      "customer_service",
      "internal_control_manager",
      "business_development_manager",
    ],
  },
  unverified_customer: {
    path: "/customers/unverified",
    name: "UnverifiedCustomers",
    requiresAuth: true,
    title: "Customer Verification",
    canAcceess: [
      "super_admin",
      "accountant",
      "customer_service",
      "internal_control_manager",
      "business_development_manager",
    ],
  },
  customer_details: {
    path: "/customers/:id",
    name: "CustomerDetails",
    requiresAuth: true,
    title: "Customer Details",
    canAcceess: [
      "super_admin",
      "accountant",
      "customer_service",
      "internal_control_manager",
      "business_development_manager",
    ],
  },
  fleet: {
    path: "/fleet-management",
    name: "FleetManagement",
    requiresAuth: true,
    title: "Fleet Management",
    canAcceess: ["super_admin", "business_development_manager"],
  },
  driver: {
    path: "/driver-management",
    name: "Driver Management",
    requiresAuth: true,
    title: "Driver Management",
    canAcceess: ["super_admin", "business_development_manager"],
  },
  wallet: {
    path: "/wallets",
    name: "Wallets",
    requiresAuth: true,
    title: "Wallets",
    canAcceess: ["super_admin", "accountant", "customer_service"],
  },
  topup_approval: {
    path: "/wallets/topup-approval",
    name: "WalletsTopupApproval",
    requiresAuth: true,
    title: "Pending TopUp Approval",
    canAcceess: ["super_admin", "accountant", "customer_service"],
  },
  credit: {
    path: "/credits",
    name: "Credits",
    requiresAuth: true,
    title: "Credits Management",
  },
  credit_repayment: {
    path: "/credits/pending-repayment",
    name: "Credits Repayment",
    requiresAuth: true,
    title: "Credits Repayment Requests",
  },
  payment: {
    path: "/payments",
    name: "Payments",
    requiresAuth: true,
    title: "Payments",
  },
};
